services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpasswd
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '5454:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: rootpasswd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  server_dev:
    container_name: server_dev
    image: oven/bun:1.1.18
    volumes:
      - './:/ichack25'
    working_dir: /ichack25
    command: bun run dev:server
    ports:
      - '5000:3000'
    depends_on:
      - postgres
    env_file:
      - ./server/.env

  admin_dev:
    container_name: admin_dev
    image: oven/bun:1.1.18
    ports:
      - '3000:3000'
    volumes:
      - './:/ichack25'
    working_dir: /ichack25
    command: bun run dev:admin
    env_file:
      - ./apps/admin/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/dev.nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - server_dev
      - admin_dev

volumes:
  postgres_data:
    name: ichack25_postgres_data
  pgadmin_data:
    name: ichack25_pgadmin_data
