services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpasswd
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '5454:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: rootpasswd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: dev_server
    volumes:
      - './server:/ichack25/server'
      - './server/node_modules:/ichack25/server/node_modules'
    ports:
      - '5000:3000'
    depends_on:
      - postgres
    env_file:
      - ./server/.env

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
      target: dev_admin
    ports:
      - '3000:3000'
    volumes:
      - './apps/admin:/ichack25/apps/admin'
      - './apps/admin/node_modules:/ichack25/apps/admin/node_modules'
    env_file:
      - ./apps/admin/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - server
      - admin

volumes:
  postgres_data:
    name: ichack25_postgres_data
  pgadmin_data:
    name: ichack25_pgadmin_data
