services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpasswd
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  website:
    container_name: website
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env.local

volumes:
  postgres_data:
    name: ichack25_postgres_data
