services:
  postgres:
    image: postgres:16
    container_name: ichack_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpasswd
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  website:
    container_name: ichack_website
    build:
      context: .
      target: website
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - PGUSER=admin
      - PGPASSWORD=rootpasswd
      - PGDB=postgres
      - PGHOST=posgres
      - PGPORT=5432

  landing:
    container_name: ichack_landing
    build:
      context: .
      target: landing
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    environment:
      - PGUSER=admin
      - PGPASSWORD=rootpasswd
      - PGDB=postgres
      - PGHOST=posgres
      - PGPORT=5432

volumes:
  postgres_data:
    name: ichack_postgres_data
