services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpasswd
      POSTGRES_DB: ichack25
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - '5000:3000'
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '5454:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: rootpasswd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  pgadmin_data:
