name: build-test

on:
  push:
    branches-ignore:
      - main
      - production

jobs:
  checkFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.44

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./bun.lock
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check format
        run: bun run format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.44

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./bun.lock
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

  testServer:
    needs: build
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.44

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./bun.lock
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Upload schema
        run: bun run backend:push-schema
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDB: postgres
          PGHOST: localhost
          PGPORT: 5432
          PGCA: ''

      - name: Run tests
        run: bun test server
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDB: postgres
          PGHOST: localhost
          PGPORT: 5432

  checkSchema:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.44

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./bun.lock
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check schema
        run: bun run backend:check-schema
