name: deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    outputs:
      base-tag: ${{ steps.tags.outputs.base-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Upload landing static files artifact
        uses: actions/upload-artifact@v4
        with:
          name: landing-static
          path: packages/www/dist

      - name: Fetch and set tags
        id: tags
        run: |
          git fetch --tags
          latest=$(git tag --list 'v*' --sort=-creatordate | grep -v -- '-staging' | head -n 1)

          echo "base-tag=$latest" >> "$GITHUB_OUTPUT"
          echo "Latest Production Tag: $latest"

  deploy-landing-prod:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download landing artifact
        uses: actions/download-artifact@v4
        with:
          name: landing-static
          path: dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ichack25 --branch=production

  generateChangelog:
    needs: [deploy-landing-prod, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        run: |
          base_tag=$(echo ${{ needs.build.outputs.base-tag }})

          echo "Generating changelog since $base_tag"
          git log --pretty=format:"- %s (%an)" $base_tag..HEAD | tee CHANGELOG.md

      - name: Push to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          base_tag=$(echo ${{ needs.build.outputs.base-tag }})
          CHANGELOG=$(cat CHANGELOG.md)

          payload=$(jq -n \
              --arg title "Deployed to Production: ${{ github.ref_name }}" \
              --arg description "Changes since last production deployment '$base_tag':" \
              --arg changelog "$CHANGELOG" \
              --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")" \
              '{
                username: "IC Hack Changelog Bot",
                avatar_url: "https://ichack.org/favicon.ico",
                embeds: [
                  {
                    title: $title,
                    description: ($description + "\n\n" + $changelog),
                    color: 24806,
                    timestamp: $timestamp,
                    url: "https://github.com/icdocsoc/ichack"
                  }
                ]
              }'
            )

          curl -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL"
