name: deploy

on:
  push:
    tags:
      - v[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}-[0-9]+

jobs:
  build:
    outputs:
      last-prod-tag: ${{ steps.latest_tags.outputs.last }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Upload landing static files artifact
        uses: actions/upload-artifact@v4
        with:
          name: landing-static
          path: packages/www/dist

      - name: Fetch and set tags
        run: |
          git fetch --tags
          tags=$(git tag --list 'v[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}-[0-9]+' --sort=-creatordate)
          last=$(echo "$tags" | head -n 2 | tail -n 1)

          echo "::set-output name=last::$last"
          echo "Previous Prod Tag: $latest"

  deploy-landing-prod:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download landing artifact
        uses: actions/download-artifact@v4
        with:
          name: landing-static
          path: dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ichack25 --branch=production

  generateChangelog:
    needs: [deploy-landing-prod, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        run: |
          last_tag=$(echo ${{ needs.build.outputs.last-prod-tag }})

          echo "Generating changelog since $last_tag"
          git log --pretty=format:"- %s (%an)" $last_tag..HEAD | tee CHANGELOG.md

      - name: Push to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          last_tag=$(echo ${{ needs.build.outputs.last-prod-tag }})
          CHANGELOG=$(cat CHANGELOG.md)

          payload=$(jq -n \
            --arg title "Deployed to Production: ${{ github.ref_name }}" \
            --arg description "Changes since last production deployment '$last_tag':" \
            --arg changelog "$CHANGELOG" \
            --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")" \

            '{
              username: "IC Hack Changelog Bot",
              avatar_url: "https://ichack.org/favicon.ico",
              embeds: [
                {
                  title: $title,
                  description: $description + "\n\n" + $changelog,
                  color: 24806,
                  timestamp: $timestamp,
                  url: https://github.com/icdocsoc/ichack
                }
              ]
            }'
          )

          curl -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL"
